"""Export sprite metadata only; preserves all source PNG files and uploaded IDs."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def lua(value):
    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (float, int)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=True)
    if isinstance(value, list):
        return "{" + ",".join(lua(item) for item in value) + "}"
    return "{" + ",".join("[" + lua(key) + "]=" + lua(item) for key, item in value.items()) + "}"


manifest = json.loads((ROOT / "art/sprites/sprite-manifest.json").read_text(encoding="utf-8-sig"))
catalog = {
    "atlases": {atlas["id"]: {"frames": atlas["frames"], "columns": atlas["columns"],
                             "imageSize": atlas["imageSize"]}
                for atlas in manifest["atlases"]},
    "animations": manifest["animationMap"],
}
(ROOT / "game/Shared/SpriteCatalog.lua").write_text(
    "-- Generated by tools/Generate-SpriteCatalog.py. Image IDs live in SpriteImages.lua.\n"
    "return " + lua(catalog) + "\n", encoding="utf-8")
print("Exported sprite metadata; uploaded image IDs preserved.")
